###############################################################################
# Copyright (c) 2017, 2017 IBM Corp. and others
# 
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which accompanies this
# distribution and is available at https://www.eclipse.org/legal/epl-2.0/
# or the Apache License, Version 2.0 which accompanies this distribution and
# is available at https://www.apache.org/licenses/LICENSE-2.0.
#      
# This Source Code may also be made available under the following
# Secondary Licenses when the conditions for such availability set
# forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
# General Public License, version 2 with the GNU Classpath
# Exception [1] and GNU General Public License, version 2 with the
# OpenJDK Assembly Exception [2].
#    
# [1] https://www.gnu.org/software/classpath/license.html
# [2] http://openjdk.java.net/legal/assembly-exception.html
# 
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
###############################################################################

configuration: Debug
shallow_clone: true
clone_depth: 1

environment:
  GTEST_FILTER: '-*dump_test_create_dump_*:*NumaSetAffinity:*NumaSetAffinitySuspended:PortSysinfoTest.sysinfo_test0:ThreadExtendedTest.TestOtherThreadCputime'
  GTEST_COLOR: '1'
  TEST_RESULT_DIR: '%APPVEYOR_BUILD_FOLDER%\test_results'
  GTEST_OUTPUT: 'xml:%TEST_RESULT_DIR%\'

before_build:
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - cmd: cmake -Wdev -G "Visual Studio 11 2012" -DOMR_ENV_DATA32=ON -Ccmake\caches\Appveyor.cmake.

build:
  project: omr.sln
  parallel: true

test_script:
  - cmd: mkdir %TEST_RESULT_DIR%
  - cmd: ctest -V -C Debug
  - ps: scripts\Appveyor-ProcessTests.ps1
